Tycho test 1.0
eisopux/checker-framework-eclipse pull request #10
Opened 2020-04-03 20:23 UTC by GloriaWa

Trying to use maven+tycho+Travis CI
Build result screenshot attached to this draft pr

2020-04-03 20:25 UTC, GloriaWa commented
![build_result](https://user-images.githubusercontent.com/38885281/78401920-bee76980-75c7-11ea-9d09-d7c02ee29354.png)

2020-04-03 21:03 UTC, GloriaWa commented
I am not sure if this is a proper maven build...for me, it seems like the build logs are too few...hmmm...

2020-04-03 21:06 UTC, GloriaWa commented on .classpath
>  	<classpathentry kind="src" path="src"/>
The changes here will not be added to the final PR. It is the environment I am currently working with...should not be submitted to the master branch.

2020-04-03 21:06 UTC, GloriaWa commented on .settings/org.eclipse.jdt.core.prefs
> -org.eclipse.jdt.core.compiler.compliance=12
The changes here will not be added to the final PR. It is the environment I am currently working with...should not be submitted to the master branch.

2020-04-03 21:06 UTC, GloriaWa commented on META-INF/MANIFEST.MF
> -Bundle-RequiredExecutionEnvironment: JavaSE-12
The changes here will not be added to the final PR. It is the environment I am currently working with...should not be submitted to the master branch.

2020-04-09 22:58 UTC, wmdietl requested changes
@GloriaWa Can you please merge in master to resolve the merge conflicts?

2020-04-10 20:04 UTC, closed without merging